<?php
/** Run with wp eval-file on a disposable site only. Creates and removes fixtures. */
wp_set_current_user(1);
function p26_mtest($ok, $message): void { if (!$ok) throw new RuntimeException($message); echo "PASS: $message\n"; }
function p26_mreject(callable $fn, string $message): void { try { $fn(); } catch (RuntimeException $e) { echo "PASS: $message ({$e->getMessage()})\n"; return; } throw new RuntimeException("Expected rejection: $message"); }
global $wpdb;
$original_settings = p26_settings();
$original_map = get_option(P26_LEGACY_MAP);
$original_active = get_option('active_plugins');
$ids = [];
$option_name = 'migration_test_widget';
$term_id = 0; $comment_id = 0;
$orphan_id = 999999998;
$saved_adapter_options = [];
foreach (['duplicate_post_types_enabled','relevanssi_index_post_types','rewrite_rules'] as $key) $saved_adapter_options[$key] = get_option($key);
$plugin_dir = WP_PLUGIN_DIR . '/p26-legacy-fixture';
if (!is_dir($plugin_dir)) mkdir($plugin_dir);
file_put_contents($plugin_dir . '/personas.php', "<?php\n/* Plugin Name: Personas\nVersion: 3.1\n*/\n");
wp_clean_plugins_cache();
update_option('active_plugins', array_merge($original_active, ['p26-legacy-fixture/personas.php']));
foreach (['__persona', '__interest', 'migration_audience', 'migration_interest'] as $type) register_post_type($type, ['public' => true, 'show_ui' => true]);
$make = static function ($type, $title, $content = '') use (&$ids) { $id = wp_insert_post(['post_type' => $type, 'post_status' => 'publish', 'post_title' => $title, 'post_content' => wp_slash($content)]); $ids[] = $id; return $id; };
try {
    delete_option(P26_LEGACY_JOURNAL); delete_option(P26_LEGACY_COMPAT);
    update_option(P26_SETTINGS_OPTION, ['tracked' => [['post_type'=>'migration_audience','context'=>'Audience'],['post_type'=>'migration_interest','context'=>'Interests']], 'content_post_types'=>['post']]);
    update_option(P26_LEGACY_MAP, ['__persona'=>'d0','__interest'=>'d1']);
    p26_mtest(p26_legacy_plugin()['version'] === '3.1', 'Active original plugin detected by header');
    $a = $make('__persona', 'Migration parents'); $i = $make('__interest', 'Migration learning');
    $existing = $make('migration_audience', 'Existing target');
    $body = '<!-- wp:test/query {"postType":"__persona","metaQuery":{"key":"__interest","value":"' . $i . '","compare":"LIKE"},"empty":{},"list":[]} /--><p>Unchanged HTML</p>';
    $post = $make('post', 'Legacy version 3 content', $body);
    add_post_meta($post, '__persona', [(string)$a]); add_post_meta($post, '___persona', 'field_personas');
    add_post_meta($post, '__interest', [(string)$i]); add_post_meta($post, '___interest', 'field_interests');
    update_post_meta($post, P26_ALIGNMENT_META, ['dims'=>['d0'=>[$existing]]]);
    p26_sync_alignment_mirrors($post, get_post_meta($post, P26_ALIGNMENT_META, true));
    add_post_meta($post, 'unrelated', 'Keep me');
    $wpdb->insert($wpdb->postmeta, ['post_id'=>$post, 'meta_key'=>'nullable_unrelated', 'meta_value'=>null]);
    $wpdb->insert($wpdb->postmeta, ['post_id'=>$post, 'meta_key'=>'target_personas', 'meta_value'=>null]);
    p26_mtest(!p26_legacy_has_reference(null) && null === p26_legacy_decode(null), 'SQL NULL metadata is supported without coercing stored values');
    $old = $make('post', 'Legacy pre-3 content');
    add_post_meta($old, 'target_personas', [(string)$a]); add_post_meta($old, 'target_interests', [(string)$i]);
    add_post_meta($old, '_target_personas', 'field_personas');
    add_post_meta($old, 'target_personas', [(string)$existing]);
    $revision = $make('revision', 'Historical metadata');
    add_post_meta($revision, 'target_personas', ['999999999']);
    $wpdb->insert($wpdb->postmeta, ['post_id'=>$orphan_id, 'meta_key'=>'target_personas', 'meta_value'=>serialize(['999999999'])]);
    update_option('duplicate_post_types_enabled', ['post','__persona']);
    update_option('relevanssi_index_post_types', ['__interest','page']);
    update_option('rewrite_rules', ['interests/([^/]+)/?$'=>'index.php?__interest=$matches[1]']);
    add_post_meta($old, '_builder', ['query'=>['post_type'=>['__persona','__interest'], 'meta_key'=>'target_personas']]);
    update_option($option_name, ['post_type'=>'__interest', 'meta_key'=>'__persona'], false);
    $term_id = wp_insert_term('Migration term ' . wp_generate_uuid4(), 'category')['term_id'];
    $comment_id = wp_insert_comment(['comment_post_ID'=>$post,'comment_content'=>'Migration fixture']);
    add_term_meta($term_id, 'builder', ['post_type'=>'__persona']);
    add_comment_meta($comment_id, 'builder', ['meta_key'=>'target_interests']);
    $template = $make('wp_template', 'Migration template', '<!-- wp:test/query {"postType":"__interest"} /-->');
    add_post_meta($old, '_menu_item_object', '__persona');
    $before = $wpdb->get_results("SELECT * FROM {$wpdb->postmeta} WHERE post_id IN ($post,$old) ORDER BY meta_id", ARRAY_A);
    $journal = p26_legacy_simulate();
    p26_mtest(!$journal['plan']['blockers'], 'Both legacy layouts produce a clean preview: ' . implode('; ', $journal['plan']['blockers']));
    $mapping_settings = p26_settings();
    p26_mreject(static fn()=>p26_legacy_save_mapping(['__persona'=>'d0','__interest'=>'d0']), 'Invalid wizard mapping leaves settings untouched');
    p26_legacy_save_mapping(['__persona'=>'d0','__interest'=>'d1']);
    p26_mtest(p26_legacy_read_journal() === [] && p26_settings() === $mapping_settings, 'Saving wizard mapping clears stale preview without changing dimensions or scope');
    $journal = p26_legacy_simulate();
    p26_mtest($journal['plan']['preserved'] === ['revisions'=>1,'orphaned_meta'=>1], 'Revision and orphaned metadata are retained without scope or ID blockers');
    p26_mtest($journal['plan']['counts']['tagged_content'] === 2, 'Preview counts tagged content');
    p26_mtest(get_post_type($a) === '__persona' && $before === $wpdb->get_results("SELECT * FROM {$wpdb->postmeta} WHERE post_id IN ($post,$old) ORDER BY meta_id", ARRAY_A), 'Simulation leaves content and metadata byte-for-byte unchanged');
    p26_mreject(static fn()=>p26_legacy_commit('stale-token'), 'Stale token rejected');
    add_post_meta($post, 'after_preview', 'concurrent edit');
    p26_mreject(static fn()=>p26_legacy_commit($journal['token']), 'Edits since preview reject commit');
    delete_post_meta($post, 'after_preview');
    $journal = p26_legacy_simulate();
    $write_count = 0;
    $fail_query = static function ($query) use ($wpdb, &$write_count) {
        if (str_starts_with($query, "UPDATE `{$wpdb->posts}`") && ++$write_count === 2) return 'P26_INTENTIONAL_INVALID_SQL';
        return $query;
    };
    add_filter('query', $fail_query);
    $old_suppress = $wpdb->suppress_errors(true);
    p26_mreject(static fn()=>p26_legacy_commit($journal['token']), 'Mid-commit SQL failure rolls back');
    remove_filter('query', $fail_query);
    $wpdb->suppress_errors($old_suppress);
    p26_mtest($wpdb->get_var($wpdb->prepare("SELECT post_type FROM {$wpdb->posts} WHERE ID=%d", $a)) === '__persona' && p26_legacy_read_journal()['status'] === 'preview', 'Failed commit preserves source data and preview journal');
    $committed = p26_legacy_commit($journal['token']);
    p26_mtest(get_option('duplicate_post_types_enabled') === ['post','migration_audience'] && get_option('relevanssi_index_post_types') === ['migration_interest','page'], 'Verified plugin post-type lists are translated');
    p26_mtest(get_post_type($a) === 'migration_audience' && get_post_type($i) === 'migration_interest', 'Post types change while IDs stay fixed');
    p26_mtest(get_post_meta($post, P26_ALIGNMENT_META, true)['dims']['d0'] === [$existing, $a], 'Existing and legacy targets merged');
    p26_mtest(get_post_meta($post, 'p26_legacy_d0_ids', true) === [(string)$existing, (string)$a], 'Relationship aliases retain ID semantics');
    p26_mtest(in_array('Migration parents', get_post_meta($post, 'migration_audience', false), true), 'Title query mirrors generated');
    if (function_exists('get_field')) { p26_legacy_register_acf_fields(); p26_mtest(get_field('p26_legacy_d0_ids', $post) === [$existing, $a], 'ACF resolves translated fields to IDs'); }
    p26_mtest(get_post_meta($post, '__persona', true) === [(string)$a], 'Original relationships preserved');
    $after_body = get_post_field('post_content', $post);
    p26_mtest(str_contains($after_body, '"postType":"migration_audience"') && str_contains($after_body, '"key":"p26_legacy_d1_ids"') && str_contains($after_body, '"empty":{}') && str_ends_with($after_body, '<p>Unchanged HTML</p>'), 'Block attributes translated without changing HTML or JSON types');
    p26_mtest(get_option($option_name) === ['post_type'=>'migration_interest', 'meta_key'=>'p26_legacy_d0_ids'], 'Serialized option references translated safely');
    p26_mtest(get_term_meta($term_id, 'builder', true) === ['post_type'=>'migration_audience'] && get_comment_meta($comment_id, 'builder', true) === ['meta_key'=>'p26_legacy_d1_ids'], 'Term and comment metadata translated');
    p26_mtest(str_contains(get_post_field('post_content', $template), 'migration_interest'), 'Template block references translated');
    p26_mtest(get_post_meta($old, '_menu_item_object', true) === 'migration_audience', 'Navigation menu object type translated');
    p26_mtest(get_post_meta($old, '_builder', true)['query']['post_type'] === ['migration_audience','migration_interest'], 'Serialized nested postmeta references translated');
    update_option('active_plugins', $original_active);
    p26_mtest(!p26_legacy_plugin() && p26_legacy_show_wizard(), 'Recovery stays on wizard tab after legacy deactivation');
    p26_legacy_refresh_deactivated_routes();
    p26_mtest(!get_option('p26_legacy_pending_rewrite_source'), 'Routes refresh after source plugin deactivation');
    p26_legacy_sync_aliases($revision, ['dims'=>['d0'=>[$a]]]);
    p26_mtest(!metadata_exists('post',$revision,'p26_legacy_d0_ids'), 'Compatibility refresh does not change historical revision metadata');
    p26_legacy_rollback($journal['token'], true);
    p26_mtest(get_post_type($a) === 'migration_audience', 'Rollback check is read-only with legacy plugin off');
    // An unchanged mirror refresh must not invalidate the recovery snapshot.
    p26_sync_alignment_mirrors($post, get_post_meta($post, P26_ALIGNMENT_META, true));
    p26_legacy_rollback($journal['token'], true);
    add_post_meta($post, 'later_edit', 'must not overwrite');
    p26_mreject(static fn()=>p26_legacy_rollback($journal['token']), 'Rollback protects edits after commit');
    p26_mtest(get_post_type($a) === 'migration_audience', 'A rollback conflict causes no partial restoration');
    delete_post_meta($post, 'later_edit');
    p26_legacy_rollback($journal['token']);
    p26_mtest(!p26_legacy_show_wizard(), 'Wizard hides once recovery is complete and legacy is inactive');
    p26_mtest(get_post_type($a) === '__persona' && get_post_field('post_content',$post) === $body, 'Rollback restores original CPT and block bytes');
    p26_mtest($before === $wpdb->get_results("SELECT * FROM {$wpdb->postmeta} WHERE post_id IN ($post,$old) ORDER BY meta_id", ARRAY_A), 'Rollback restores exact metadata IDs, values and ordering');
    p26_mtest(get_option($option_name) === ['post_type'=>'__interest','meta_key'=>'__persona'], 'Rollback restores serialized options');
    update_option('active_plugins', array_merge($original_active, ['p26-legacy-fixture/personas.php']));
    $unknown = $make('post', 'Unknown reference', '<!-- wp:test/query {"opaque":"__persona"} /-->');
    $blocked = p26_legacy_simulate();
    p26_mtest((bool)$blocked['plan']['blockers'], 'Unknown block context blocks commit');
    p26_mreject(static fn()=>p26_legacy_commit($blocked['token']), 'Blocked preview cannot commit');
    wp_delete_post($unknown, true);
    $map = p26_legacy_mapping();
    p26_mreject(static fn()=>p26_legacy_transform('O:8:"stdClass":1:{s:3:"key";s:9:"__persona";}', $map), 'Serialized objects rejected without instantiation');
    p26_mreject(static fn()=>p26_legacy_transform(['__persona'=>1,'p26_legacy_d0_ids'=>2],$map), 'Key collisions rejected');
    $collision = $make('migration_audience', 'Migration parents');
    $blocked = p26_legacy_simulate();
    p26_mtest((bool)array_filter($blocked['plan']['blockers'], static fn($b)=>str_contains($b,'destination slug')), 'Destination slug collisions block migration');
    wp_delete_post($collision, true);
    $bad_meta = add_post_meta($post, '__persona', ['999999999']);
    $blocked = p26_legacy_simulate();
    p26_mtest(!$blocked['plan']['blockers'] && $blocked['plan']['skipped_missing'][0]['target_id'] === 999999999, 'Missing relationship IDs are reported and skipped');
    delete_metadata_by_mid('post', $bad_meta);
    $source_fixture = WPMU_PLUGIN_DIR . '/p26-migration-code-fixture.php';
    file_put_contents($source_fixture, '<?php // query __persona');
    try {
        $configured = p26_legacy_simulate();
        p26_mtest(!$configured['plan']['blockers'], 'Source text does not block migration of saved site configuration');
        p26_legacy_commit($configured['token']);
        p26_mtest(get_post_type($a) === 'migration_audience' && get_post_type($i) === 'migration_interest', 'Original records move to destinations with IDs intact');
        p26_mtest(file_get_contents($source_fixture) === '<?php // query __persona', 'Migration leaves component source files unchanged');
        p26_legacy_rollback($configured['token']);
    } finally { unlink($source_fixture); }
    $settings_before_scope = p26_settings();
    update_option(P26_SETTINGS_OPTION, array_merge($settings_before_scope, ['content_post_types'=>[]]));
    $scope = p26_legacy_simulate();
    p26_mtest($scope['plan']['scope_required'] === ['post'=>2], 'Missing scope is grouped by real tagged content type');
    p26_legacy_include_detected_scope();
    p26_mtest(p26_settings() === $settings_before_scope && p26_legacy_read_journal() === [], 'Scope action preserves dimensions and invalidates preview');
    p26_mtest(get_post_meta($revision,'target_personas',true) === ['999999999'], 'Historic revision tags remain untouched');
    // A realistic incompressible field creates a before/after snapshot well over 4 MiB.
    $large_value = base64_encode(random_bytes(1800000));
    add_post_meta($post, 'large_unrelated_payload', $large_value);
    $large = p26_legacy_simulate();
    p26_mtest(strlen(serialize($large['plan'])) > 4194304, 'Large fixture exceeds the former 4 MiB limit');
    $manifest = unserialize($wpdb->get_var($wpdb->prepare("SELECT option_value FROM {$wpdb->options} WHERE option_name=%s", P26_LEGACY_JOURNAL)), ['allowed_classes'=>false]);
    p26_mtest($manifest['_snapshot']['chunks'] > 1 && !isset($manifest['plan']), 'Large recovery data is stored in multiple non-autoloaded chunks');
    $chunk_name = P26_LEGACY_CHUNK_PREFIX . '000000';
    $chunk_value = $wpdb->get_var($wpdb->prepare("SELECT option_value FROM {$wpdb->options} WHERE option_name=%s", $chunk_name));
    $wpdb->delete($wpdb->options, ['option_name'=>$chunk_name]);
    p26_mreject(static fn()=>p26_legacy_commit($large['token']), 'Missing snapshot chunk blocks commit');
    $wpdb->insert($wpdb->options, ['option_name'=>$chunk_name,'option_value'=>$chunk_value,'autoload'=>'off']);
    $wpdb->update($wpdb->options, ['option_value'=>base64_encode('corrupt')], ['option_name'=>$chunk_name]);
    p26_mreject(static fn()=>p26_legacy_commit($large['token']), 'Corrupted snapshot blocks commit');
    $wpdb->update($wpdb->options, ['option_value'=>$chunk_value], ['option_name'=>$chunk_name]);
    $fail_chunk = static fn($query) => str_starts_with($query, 'INSERT INTO') && str_contains($query, P26_LEGACY_CHUNK_PREFIX . '000001') ? 'P26_INTENTIONAL_INVALID_SQL' : $query;
    add_filter('query', $fail_chunk);
    $old_suppress = $wpdb->suppress_errors(true);
    p26_mreject(static fn()=>p26_legacy_commit($large['token']), 'Failed chunk write rolls back the entire migration');
    remove_filter('query', $fail_chunk); $wpdb->suppress_errors($old_suppress);
    p26_mtest(p26_legacy_read_journal() === $large && get_post_type($a) === '__persona', 'Failed chunk write retains the complete prior preview and source posts');
    p26_legacy_commit($large['token']);
    p26_legacy_rollback($large['token']);
    p26_mtest(get_post_meta($post,'large_unrelated_payload',true) === $large_value && get_post_type($a) === '__persona', 'Large snapshot commits and rolls back without changing unrelated bytes');
    delete_post_meta($post, 'large_unrelated_payload');
    // Backward compatibility with journals written before chunked storage.
    $legacy = p26_legacy_simulate();
    $wpdb->update($wpdb->options, ['option_value'=>serialize($legacy)], ['option_name'=>P26_LEGACY_JOURNAL]);
    p26_mtest(p26_legacy_read_journal() === $legacy, 'Existing single-option journals remain readable');
    p26_legacy_commit($legacy['token']);
    p26_legacy_rollback($legacy['token']);
    p26_mtest(get_post_type($a) === '__persona', 'Existing preview upgrades to chunked storage and rolls back');
    update_option(P26_LEGACY_MAP, ['__persona'=>'d0','__interest'=>'d0']);
    p26_mreject(static fn()=>p26_legacy_simulate(), 'Duplicate destination rejected');
} finally {
    delete_option(P26_LEGACY_COMPAT); p26_legacy_delete_journal(); delete_option($option_name);
    if ($term_id) wp_delete_term($term_id, 'category');
    if ($comment_id) wp_delete_comment($comment_id, true);
    foreach ($ids as $id) wp_delete_post($id, true);
    $wpdb->delete($wpdb->postmeta, ['post_id'=>$orphan_id]);
    foreach ($saved_adapter_options as $key=>$value) { if (false === $value) delete_option($key); else update_option($key,$value); }
    update_option(P26_SETTINGS_OPTION, $original_settings);
    if (false === $original_map) delete_option(P26_LEGACY_MAP); else update_option(P26_LEGACY_MAP, $original_map);
    update_option('active_plugins', $original_active);
    unlink($plugin_dir . '/personas.php'); rmdir($plugin_dir); wp_clean_plugins_cache();
    p26_rebuild_personalize_css();
}
